/**
 * [pure] — the theme token data. No DOM, no react, no electron.
 *
 * Generated from the design handoff prototype (`SeaShell Themes.dc.html`) by
 * extracting its `THEMES` literal rather than transcribing it, so every value
 * here is byte-for-byte what the design renders. Seven themes, 82 distinct
 * custom properties between them.
 *
 * Themes set colour and shape only. Nothing here touches a dimension:
 * `--ui-scale` and everything derived from it belongs to the zoom system, and
 * a theme that resized the chrome would fight it.
 *
 * Themes deliberately define different subsets of the token set. That is the
 * source of the one bug worth knowing about here, and `applyTheme` in
 * apply.ts is what handles it.
 */

export interface Theme {
  /** Short name for the picker. */
  label: string
  /** Full name, for the row's title. */
  name: string
  /** One line on what the theme is going for. */
  note: string
  vars: Record<string, string>
}

export type ThemeKey = 'homebrew' | 'nautical' | 'retro' | 'mac' | 'macDark' | 'hacker' | 'aero'

export const THEMES: Record<ThemeKey, Theme> = {
  homebrew: {
    label: 'Current',
    name: 'Current build — Homebrew green',
    note: 'The app as it ships today, rebuilt from styles.css: green on black, 1px chrome lines, Finder-style tree rows, cards in the rail above the explorer.',
    vars: {
      '--fu': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
      '--fm': "'SF Mono', Menlo, monospace",
      '--chrome': '#0a0f0a',
      '--chromeAlt': '#060a06',
      '--line': '#1c2c1c',
      '--text': '#b9f5ae',
      '--dim': '#6ea865',
      '--faint': '#5c8551',
      '--accent': '#28fe14',
      '--onAccent': '#000',
      '--barBg': '#0a0f0a',
      '--barPadL': '78px',
      '--headBg': '#0a0f0a',
      '--sideBg': '#0a0f0a',
      '--treeBg': '#0a0f0a',
      '--gridBg': '#060a06',
      '--termBg': '#000000',
      '--termFg': '#28fe14',
      '--paneBg': '#000000',
      '--paneRadius': '4px',
      '--paneBorder': '#1c2c1c',
      '--paneTitleBg': '#0a0f0a',
      '--paneTitleOn': '#1a1f26',
      '--cardBg': '#161c22',
      '--cardText': '#b9f5ae',
      '--cardDim': '#5c8551',
      '--cardRadius': '8px',
      '--cardBorder': '#1c2c1c',
      '--cardShadow': '0 8px 24px #000a',
      '--cardRotate': '0deg',
      '--btnBg': '#262d35',
      '--btnText': '#b9f5ae',
      '--btnRadius': '4px',
      '--btnBorder': '#1c2c1c',
      '--primaryBg': '#1f6f14',
      '--primaryText': '#eafce7',
      '--primaryBorder': '#2c8f1e',
      '--body': '#0e1116',
      '--sunken': '#0a0d11',
      '--select': '#2c68d0',
      '--winRadius': '10px',
      '--winBorder': '1px solid #1c2c1c',
      '--winShadow': '0 30px 80px #000c',
      '--tabRadius': '0px',
      '--tabOnBg': '#060a06',
      '--tabOnMark': 'inset 0 -2px 0 #28fe14',
      '--g': '#35d06b',
      '--c': '#33bbc8',
      '--y': '#e5a83c',
      '--r': '#ff5f56',
      '--b': '#5a8dee',
      '--m': '#b57bff',
      '--gr': '#5c8551',
    },
  },
  nautical: {
    label: 'Nautical',
    name: 'Nautical Brass — the SeaShell default',
    note: 'Oxidized teal hull, brass hairlines, engraved caps. Restrained: the instrument-panel language lives in the 1px edges and the brass accent, not in texture.',
    vars: {
      '--fu': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
      '--fm': "'SF Mono', Menlo, monospace",
      '--chrome': '#0d1a1c',
      '--chromeAlt': '#091416',
      '--line': '#22393b',
      '--text': '#dae7e4',
      '--dim': '#93aeac',
      '--faint': '#6d8a88',
      '--accent': '#d0a63a',
      '--onAccent': '#14100a',
      '--barBg': '#102123',
      '--barPadL': '78px',
      '--barImg': 'linear-gradient(#16292b, #0d1a1c)',
      '--barShadow': 'inset 0 1px 0 #2e4b4d',
      '--headBg': '#0f1e20',
      '--sideBg': '#0c1a1c',
      '--treeBg': '#0b1719',
      '--gridBg': '#071214',
      '--termBg': '#050f11',
      '--termFg': '#cfe3df',
      '--paneBg': '#050f11',
      '--paneRadius': '5px',
      '--paneBorder': '#22393b',
      '--paneTitleBg': '#0f1f21',
      '--paneTitleOn': '#16292b',
      '--cardBg': '#122629',
      '--cardText': '#dae7e4',
      '--cardDim': '#7d9997',
      '--cardRadius': '6px',
      '--cardBorder': '#2b4a4c',
      '--cardShadow': '0 6px 18px #0007, inset 0 1px 0 #2e4b4d',
      '--cardRotate': '0deg',
      '--btnBg': '#1a3134',
      '--btnText': '#dae7e4',
      '--btnRadius': '4px',
      '--btnBorder': '#2e4b4d',
      '--primaryBg': '#a8821f',
      '--primaryText': '#1b1608',
      '--primaryBorder': '#d0a63a',
      '--body': '#08171a',
      '--sunken': '#071417',
      '--select': '#1f5b63',
      '--winRadius': '10px',
      '--winBorder': '1px solid #24403f',
      '--winShadow': '0 30px 80px #000c',
      '--tabRadius': '0px',
      '--tabOnBg': '#0b1719',
      '--tabOnMark': 'inset 0 -2px 0 #d0a63a',
      '--g': '#5ec89a',
      '--c': '#4fb6c4',
      '--y': '#d0a63a',
      '--r': '#e0705f',
      '--b': '#6f9fd0',
      '--m': '#a98ac9',
      '--gr': '#6d8a88',
    },
  },
  retro: {
    label: 'Retro CRT',
    name: 'Retro CRT — phosphor, scanlines, paper',
    note: 'Beige-plastic bezels around real CRT glass: green phosphor with a soft bloom, 3px scanlines and a tube vignette. Cards still arrive as paper slips on the desk, and the explorer is a card-index drawer.',
    vars: {
      '--fu': "'Iowan Old Style', Georgia, 'Times New Roman', serif",
      '--fm': "'Courier New', Courier, monospace",
      '--chrome': '#c9b795',
      '--chromeAlt': '#bda882',
      '--line': '#8a7450',
      '--text': '#2c2317',
      '--dim': '#5d4c31',
      '--faint': '#7b6844',
      '--accent': '#8a3b1f',
      '--onAccent': '#f6efdd',
      '--barBg': '#c9b795',
      '--barPadL': '78px',
      '--l1': '#b7503a',
      '--l2': '#c98f2f',
      '--l3': '#5f8a4a',
      '--lightRing': 'inset 0 -1px 1px #00000040, 0 1px 0 #ffffff70',
      '--barImg': 'linear-gradient(#d8c8a8, #bda882)',
      '--barShadow': 'inset 0 1px 0 #e6d9bd',
      '--pullH': '22px',
      '--pullBg': '#8f6f49',
      '--pullImg': 'linear-gradient(#a8895f, #7d5f3c)',
      '--pullBorder': '1px solid #6b542f',
      '--pullGrip': '7px',
      '--pullGripBg': '#c9a44e',
      '--pullGripImg': 'linear-gradient(#e8cb8c, #a8842e)',
      '--pullGripShadow': 'inset 0 1px 0 #f6e5bb, 0 1px 2px #00000070',
      '--headBg': '#b39a6c',
      '--sideBg': '#8a6a45',
      '--sideImg': 'repeating-linear-gradient(90deg, #8a6a45 0 6px, #815f3e 6px 12px)',
      '--sideShadow': 'inset -6px 0 12px #00000030',
      '--treeBg': '#e8dcc0',
      '--treeImg': 'repeating-linear-gradient(#e8dcc0 0 24px, #dfd1b0 24px 25px)',
      '--gridBg': '#4a3323',
      '--gridImg': 'repeating-linear-gradient(96deg, #4a3323 0 22px, #452f21 22px 44px)',
      '--termBg': '#060b06',
      '--termFg': '#5cf07a',
      '--paneBg': '#060b06',
      '--paneRadius': '7px',
      '--paneBorder': '#3a2b1c',
      '--paneTitleBg': '#cbbb96',
      '--paneTitleOn': '#e0d1ab',
      '--cardBg': '#f6efdb',
      '--cardText': '#2c2317',
      '--cardDim': '#7b6844',
      '--cardRadius': '2px',
      '--cardBorder': '#cbb98f',
      '--cardShadow': '0 10px 16px #00000045, 0 2px 3px #00000030',
      '--cardRotate': '-0.5deg',
      '--btnBg': '#e2d5b4',
      '--btnText': '#2c2317',
      '--btnRadius': '2px',
      '--btnBorder': '#a08a5f',
      '--primaryBg': '#8a3b1f',
      '--primaryText': '#f6efdd',
      '--primaryBorder': '#6d2d16',
      '--body': '#f2e9d2',
      '--sunken': '#fffaea',
      '--select': '#8a3b1f',
      '--winRadius': '6px',
      '--winBorder': '1px solid #6b542f',
      '--winShadow': '0 34px 70px #000000a0',
      '--tabRadius': '5px 5px 0 0',
      '--tabOnBg': '#e6d9bd',
      '--tabOnMark': 'inset 0 -2px 0 #8a3b1f',
      '--g': '#5cf07a',
      '--c': '#7cf5c8',
      '--y': '#c8ff86',
      '--r': '#ffa06a',
      '--b': '#8ceccb',
      '--m': '#a6f79a',
      '--gr': '#3f8a52',
    },
  },
  mac: {
    label: 'macOS Light',
    name: 'Modern — macOS companion, light',
    note: 'Light vibrancy chrome around dark terminals: 12px radii, hairline separators, soft elevation, and a single system accent doing all the signalling.',
    vars: {
      '--fu': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
      '--fm': "'SF Mono', Menlo, monospace",
      '--chrome': '#f2f2f5',
      '--chromeAlt': '#eaeaee',
      '--line': '#dcdce1',
      '--text': '#1d1d1f',
      '--dim': '#6e6e73',
      '--faint': '#98989d',
      '--accent': '#0a84ff',
      '--onAccent': '#ffffff',
      '--barBg': '#ececed',
      '--barPadL': '78px',
      '--barImg': 'linear-gradient(#f4f4f6, #e9e9ec)',
      '--headBg': '#f2f2f5',
      '--sideBg': '#f5f5f7',
      '--treeBg': '#f5f5f7',
      '--gridBg': '#e8e8ec',
      '--termBg': '#1c1c1e',
      '--termFg': '#e8e8ed',
      '--paneBg': '#1c1c1e',
      '--paneRadius': '10px',
      '--paneBorder': '#d2d2d7',
      '--paneTitleBg': '#f7f7f9',
      '--paneTitleOn': '#ffffff',
      '--cardBg': '#ffffff',
      '--cardText': '#1d1d1f',
      '--cardDim': '#8e8e93',
      '--cardRadius': '12px',
      '--cardBorder': '#e2e2e7',
      '--cardShadow': '0 6px 20px #00000014, 0 1px 2px #0000001f',
      '--cardRotate': '0deg',
      '--btnBg': '#ffffff',
      '--btnText': '#1d1d1f',
      '--btnRadius': '7px',
      '--btnBorder': '#d2d2d7',
      '--primaryBg': '#0a84ff',
      '--primaryText': '#ffffff',
      '--primaryBorder': '#0a84ff',
      '--body': '#ffffff',
      '--sunken': '#ffffff',
      '--select': '#0a84ff',
      '--winRadius': '12px',
      '--winBorder': '1px solid #d2d2d7',
      '--winShadow': '0 40px 90px #00000055',
      '--tabRadius': '8px',
      '--tabOnBg': '#ffffff',
      '--tabOnMark': '0 1px 3px #00000018',
      '--g': '#32d74b',
      '--c': '#64d2ff',
      '--y': '#ffd60a',
      '--r': '#ff453a',
      '--b': '#0a84ff',
      '--m': '#bf5af2',
      '--gr': '#8e8e93',
    },
  },
  macDark: {
    label: 'macOS Dark',
    name: 'Modern — macOS companion, dark',
    note: 'The same geometry in dark vibrancy: graphite chrome, 12px radii, hairline separators one step lighter than the surface, and the terminal now sitting flush with the window instead of against it.',
    vars: {
      '--fu': "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif",
      '--fm': "'SF Mono', Menlo, monospace",
      '--chrome': '#2a2a2c',
      '--chromeAlt': '#232325',
      '--line': '#3a3a3d',
      '--text': '#f2f2f7',
      '--dim': '#98989d',
      '--faint': '#6e6e73',
      '--accent': '#0a84ff',
      '--onAccent': '#ffffff',
      '--barBg': '#2e2e30',
      '--barPadL': '78px',
      '--barImg': 'linear-gradient(#343436, #2a2a2c)',
      '--headBg': '#2a2a2c',
      '--sideBg': '#252527',
      '--treeBg': '#252527',
      '--gridBg': '#1a1a1c',
      '--termBg': '#1c1c1e',
      '--termFg': '#e8e8ed',
      '--paneBg': '#1c1c1e',
      '--paneRadius': '10px',
      '--paneBorder': '#3a3a3d',
      '--paneTitleBg': '#2a2a2c',
      '--paneTitleOn': '#3a3a3d',
      '--cardBg': '#2c2c2e',
      '--cardText': '#f2f2f7',
      '--cardDim': '#98989d',
      '--cardRadius': '12px',
      '--cardBorder': '#3a3a3d',
      '--cardShadow': '0 6px 20px #00000066, 0 1px 2px #00000080',
      '--cardRotate': '0deg',
      '--btnBg': '#3a3a3d',
      '--btnText': '#f2f2f7',
      '--btnRadius': '7px',
      '--btnBorder': '#4a4a4e',
      '--primaryBg': '#0a84ff',
      '--primaryText': '#ffffff',
      '--primaryBorder': '#0a84ff',
      '--body': '#1c1c1e',
      '--sunken': '#1c1c1e',
      '--select': '#0a84ff',
      '--winRadius': '12px',
      '--winShadow': '0 40px 90px #000000aa',
      '--tabRadius': '8px',
      '--tabOnBg': '#3a3a3d',
      '--tabOnMark': '0 1px 3px #00000066',
      '--g': '#32d74b',
      '--c': '#64d2ff',
      '--y': '#ffd60a',
      '--r': '#ff453a',
      '--b': '#0a84ff',
      '--m': '#bf5af2',
      '--gr': '#8e8e93',
    },
  },
  hacker: {
    label: 'Hacker',
    name: 'Hacker — monospace all the way down',
    note: 'Everything is the terminal: the chrome takes the same mono face as the panes, every corner is square, and the only colours are phosphor green, alert magenta and black. Text carries a faint bloom so the screen reads as emissive rather than printed.',
    vars: {
      '--fu': "'SF Mono', Menlo, Consolas, monospace",
      '--fm': "'SF Mono', Menlo, Consolas, monospace",
      '--chrome': '#050505',
      '--chromeAlt': '#000000',
      '--line': '#173a20',
      '--text': '#c8ffd4',
      '--dim': '#4ee87a',
      '--faint': '#2c7c44',
      '--accent': '#00ff41',
      '--onAccent': '#001206',
      '--barBg': '#050505',
      '--barPadL': '78px',
      '--barImg': 'linear-gradient(#0a0f0a, #050505)',
      '--barShadow': 'inset 0 -1px 0 #123a1c',
      '--lightRadius': '0px',
      '--l1': '#ff0055',
      '--l2': '#faff00',
      '--l3': '#00ff41',
      '--headBg': '#050505',
      '--sideBg': '#040404',
      '--treeBg': '#000000',
      '--gridBg': '#000000',
      '--termBg': '#000000',
      '--termFg': '#00ff41',
      '--glow': '0 0 5px rgba(0,255,65,.45)',
      '--paneBg': '#000000',
      '--paneRadius': '0px',
      '--paneBorder': '#173a20',
      '--paneTitleBg': '#070b07',
      '--paneTitleOn': '#0d1f11',
      '--cardBg': '#050805',
      '--cardText': '#c8ffd4',
      '--cardDim': '#2c7c44',
      '--cardRadius': '0px',
      '--cardBorder': '#1d4c2a',
      '--cardShadow': '0 0 12px rgba(0,255,65,.09), 0 6px 18px #000',
      '--cardRotate': '0deg',
      '--btnBg': '#0b1a0f',
      '--btnText': '#8dffab',
      '--btnRadius': '0px',
      '--btnBorder': '#1f5c31',
      '--primaryBg': '#00ff41',
      '--primaryText': '#001206',
      '--primaryBorder': '#00ff41',
      '--body': '#020402',
      '--sunken': '#000000',
      '--select': '#0f4a22',
      '--winRadius': '0px',
      '--winShadow': '0 0 34px rgba(0,255,65,.1), 0 30px 80px #000',
      '--tabRadius': '0px',
      '--tabOnBg': '#0d1f11',
      '--tabOnMark': 'inset 0 -2px 0 #00ff41',
      '--g': '#00ff41',
      '--c': '#00e5ff',
      '--y': '#faff00',
      '--r': '#ff0055',
      '--b': '#38a1ff',
      '--m': '#ff00d4',
      '--gr': '#2c7c44',
    },
  },
  aero: {
    label: 'Aero Glass',
    name: 'Aero Glass — the Windows 7 era',
    note: 'Frosted blue glass chrome, gradient panel headers, beveled buttons and a 6px radius on everything — the late-2000s desktop look, rebuilt from scratch.',
    vars: {
      '--fu': "'Segoe UI', Tahoma, Geneva, sans-serif",
      '--fm': "Consolas, 'Courier New', monospace",
      '--chrome': '#dceaf7',
      '--chromeAlt': '#cddff0',
      '--line': '#8fb3d4',
      '--text': '#10233a',
      '--dim': '#3d5e80',
      '--faint': '#6b8aab',
      '--accent': '#2b7cd3',
      '--onAccent': '#ffffff',
      '--barBg': 'rgba(206, 230, 250, .34)',
      /* 78px like every other theme, not the prototype's 14px. Aero's mock
         drew its own window buttons on the right, which the handoff calls
         illustrative of the era rather than a spec — the real window still has
         macOS traffic lights on the left, and 14px put the first tab under
         them. */
      '--barPadL': '78px',
      '--barImg': 'linear-gradient(rgba(255,255,255,.5) 0%, rgba(210,232,252,.16) 48%, rgba(140,185,228,.24) 52%, rgba(205,228,250,.3) 100%)',
      '--glassBlur': 'blur(22px) saturate(190%) brightness(1.06)',
      '--lightsDisplay': 'none',
      '--winCtlDisplay': 'flex',
      '--deskImg': 'linear-gradient(114deg, rgba(255,255,255,0) 26%, rgba(215,245,255,.72) 38%, rgba(255,255,255,0) 47%), radial-gradient(46% 62% at 74% 16%, rgba(150,240,255,.85), rgba(0,0,0,0) 68%), radial-gradient(52% 48% at 12% 88%, rgba(90,255,215,.5), rgba(0,0,0,0) 70%), radial-gradient(120% 110% at 30% 22%, #6fc4f0 0%, #2f7fc4 36%, #14508f 68%, #0a2b52 100%)',
      '--deskOp': '1',
      '--barShadow': 'inset 0 1px 0 #ffffffcc',
      '--headBg': 'rgba(232, 243, 255, .3)',
      '--headImg': 'linear-gradient(rgba(240,247,255,.4), rgba(219,233,247,.2))',
      '--sideBg': 'rgba(238, 247, 255, .46)',
      '--treeBg': 'rgba(255, 255, 255, .66)',
      '--gridBg': 'rgba(110, 155, 200, .18)',
      '--gridImg': 'linear-gradient(160deg, rgba(168,198,224,.34), rgba(90,130,175,.4))',
      '--termBg': '#04121e',
      '--termFg': '#d7e6f2',
      '--paneBg': '#04121e',
      '--paneRadius': '6px',
      '--paneBorder': '#5b87b3',
      '--paneTitleBg': '#cfe3f7',
      '--paneTitleOn': '#e8f3ff',
      '--cardBg': '#f4f9fe',
      '--cardText': '#10233a',
      '--cardDim': '#5b7794',
      '--cardRadius': '6px',
      '--cardBorder': '#7ba2c9',
      '--cardShadow': '0 4px 12px #0e2a4640, inset 0 1px 0 #ffffff',
      '--cardRotate': '0deg',
      '--btnBg': '#e6f0fa',
      '--btnImg': 'linear-gradient(#fdfefe, #e3edf7 48%, #d3e2f1 52%, #eaf3fb)',
      '--btnText': '#10233a',
      '--btnRadius': '4px',
      '--btnBorder': '#7ba2c9',
      '--primaryBg': '#2b7cd3',
      '--primaryImg': 'linear-gradient(#7ec0f5, #2b7cd3 52%, #1f66b4)',
      '--primaryText': '#ffffff',
      '--primaryBorder': '#1c5a9e',
      '--body': '#ffffff',
      '--sunken': '#ffffff',
      '--select': '#3399ff',
      '--winRadius': '8px',
      '--winBorder': '1px solid #ffffff80',
      '--winShadow': '0 0 0 1px #33608f, 0 30px 70px #0a1e3388',
      '--tabRadius': '5px 5px 0 0',
      '--tabOnBg': '#f3f9ff',
      '--tabOnImg': 'linear-gradient(#ffffff, #e6f1fb)',
      '--tabOnMark': 'inset 0 -2px 0 #2b7cd3',
      '--g': '#6cc24a',
      '--c': '#4fc3d9',
      '--y': '#e0a500',
      '--r': '#e04b3f',
      '--b': '#3d8fdd',
      '--m': '#a071cf',
      '--gr': '#6b8aab',
    },
  },}

/** Render order for the picker, and the order the design presents them in. */
export const THEME_ORDER: readonly ThemeKey[] = [
  'homebrew',
  'nautical',
  'retro',
  'mac',
  'macDark',
  'hacker',
  'aero',
]

/**
 * Terminal palettes, the one axis that also has to reach xterm.
 *
 * `native` means the theme's own terminal colours; the three below override
 * them wholesale.
 */
export type PaletteKey = 'native' | 'solar' | 'amber' | 'ice'

export const PALETTES: Record<Exclude<PaletteKey, 'native'>, Record<string, string>> = {
  solar: { '--termBg': '#04212b', '--termFg': '#93a1a1', '--g': '#859900', '--c': '#2aa198', '--y': '#b58900', '--r': '#dc322f', '--b': '#268bd2', '--m': '#6c71c4', '--gr': '#586e75' },
  amber: { '--termBg': '#140f04', '--termFg': '#ffb000', '--g': '#ffb000', '--c': '#e09400', '--y': '#ffd171', '--r': '#ff7b3d', '--b': '#c98a1f', '--m': '#ffc94d', '--gr': '#8a6216' },
  ice: { '--termBg': '#0b1016', '--termFg': '#d6e2ee', '--g': '#8fd6a8', '--c': '#8fc8dd', '--y': '#e6cf8f', '--r': '#e08b8b', '--b': '#89a9dc', '--m': '#b7a4dd', '--gr': '#6b7885' },
}

export const PALETTE_ORDER: readonly PaletteKey[] = ['native', 'solar', 'amber', 'ice']

export const PALETTE_LABELS: Record<PaletteKey, string> = {
  native: 'Theme native',
  solar: 'Solar',
  amber: 'Amber mono',
  ice: 'Ice',
}

/** How a pane's frame is drawn. `theme` defers to each theme's own default. */
export type PaneStyleKey = 'theme' | 'hairline' | 'bezel' | 'floating' | 'slab'

export const PANE_STYLES: Record<Exclude<PaneStyleKey, 'theme'>, { label: string; vars: Record<string, string> }> = {
  hairline: { label: 'Hairline', vars: {} },
  bezel: {
    label: 'Bezel',
    vars: {
      '--paneFramePad': '7px',
      '--paneFrameBg': 'var(--paneTitleBg)',
      '--paneBorderW': '1px',
      '--paneRadius': '11px',
      '--titleRadius': '5px',
      '--termRadius': '5px',
      '--paneShadow':
        'inset 0 1px 0 rgba(255,255,255,.22), inset 0 -1px 0 rgba(0,0,0,.28), 0 3px 8px rgba(0,0,0,.34)',
    },
  },
  floating: {
    label: 'Floating',
    vars: {
      '--paneBorderW': '0px',
      '--paneRadius': '13px',
      '--termRadius': '0px',
      /* The gutter between panes is 9px and collects BOTH neighbours'
         shadows at close range, so the blur has to stay under half the
         gutter width or the desk between panes turns into a dark channel.
         The original 32px/40% pair measured ~150 grey on macOS Light's
         #e8e8ec desk; this contact shadow leaves it above 205. */
      '--paneShadow': '0 2px 8px rgba(0,0,0,.22)',
    },
  },
  slab: {
    label: 'Slab',
    vars: { '--paneRadius': '0px', '--paneBorderW': '2px', '--termRadius': '0px', '--paneShadow': 'none' },
  },
}

export const PANE_STYLE_ORDER: readonly PaneStyleKey[] = [
  'theme',
  'hairline',
  'bezel',
  'floating',
  'slab',
]

/** Each theme's own frame treatment, used when paneStyle is 'theme'. */
export const THEME_PANE_STYLE: Record<ThemeKey, Exclude<PaneStyleKey, 'theme'>> = {
  homebrew: 'hairline',
  nautical: 'hairline',
  retro: 'bezel',
  mac: 'floating',
  macDark: 'floating',
  hacker: 'slab',
  aero: 'hairline',
}

export type CrtKey = 'theme' | 'on' | 'off'

/**
 * The CRT glass layers. Four effects over the terminal, plus the tube vignette.
 * On for `retro` by default, but independent of theme: CRT glass over macOS
 * Dark is a legitimate thing to want.
 */
export const CRT: Record<string, string> = {
  '--scanImg':
    'repeating-linear-gradient(to bottom, rgba(0,0,0,.34) 0px, rgba(0,0,0,.34) 1px, rgba(0,0,0,0) 1px, rgba(0,0,0,0) 3px)',
  '--scanSize': '100% 3px',
  '--scanOp': '1',
  '--scanAnim': 'crtCrawl 1.8s linear infinite',
  '--crtAnim': 'crtFlicker 5.5s ease-in-out infinite',
  '--glassImg':
    'radial-gradient(118% 96% at 50% 50%, rgba(0,0,0,0) 54%, rgba(0,0,0,.5) 100%), linear-gradient(rgba(255,255,255,.06), rgba(255,255,255,0) 38%)',
  '--glassOp': '1',
  '--bandImg':
    'linear-gradient(rgba(255,255,255,0), rgba(255,255,255,.05) 45%, rgba(255,255,255,0))',
  '--rollAnim': 'crtRoll 8s linear infinite',
  '--crtInset': 'inset 0 0 54px rgba(0,0,0,.9)',
}

/**
 * Accents are a fixed palette, not a colour picker, and what is stored is the
 * key rather than the literal.
 *
 * Same reasoning already written into panes/colors.ts: an arbitrary hex
 * regularly lands on something invisible against the chrome, and a stored key
 * survives a palette revision where a stored literal strands itself.
 */
export const ACCENTS: ReadonlyArray<{ key: string; label: string }> = [
  { key: '#28fe14', label: 'Homebrew green' },
  { key: '#c9a227', label: 'Brass' },
  { key: '#0a84ff', label: 'Blue' },
  { key: '#e5533d', label: 'Signal red' },
  { key: '#b57bff', label: 'Violet' },
  { key: '#33bbc8', label: 'Cyan' },]
